name: CI
on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install ZetaSploit
        run: bash install.sh
      - name: Perform tests
        run: python3 -c 'from test.tester import tester;tester = tester(); tester.perform_tests()'
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install ZetaSploit
        run: bash install.sh
      - name: Perform tests
        run: python3 -c 'from test.tester import tester;tester = tester(); tester.perform_tests()'
