name: CI
on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install ZetaSploit
        run: bash install.sh
      - name: Run ZetaSploit
        run: echo "exit" | sudo zsf
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install ZetaSploit
        run: bash install.sh
      - name: Run ZetaSploit
        run: echo "exit" | sudo zsf
