name: CI
on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Upload ZetaSploit
        run: sudo mkdir /opt/zsf; sudo cp -r * /opt/zsf
      - name: Install ZetaSploit
        run: cd /opt/zsf; bash install.sh
      - name: Perform tests
        run: cd /opt/zsf; python3 tester.py; echo 'exit' | sudo zsf
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Upload ZetaSploit
        run: sudo mkdir /opt/zsf; sudo cp -r * /opt/zsf
      - name: Install ZetaSploit
        run: cd /opt/zsf; bash install.sh
      - name: Perform tests
        run: cd /opt/zsf; python3 tester.py; echo 'exit' | sudo zsf
