name: CI
on: [pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install ZetaSploit
        run: bash install.sh
      - name: Perform tests
        run: python3 perform_tests.py
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install ZetaSploit
        run: bash install.sh
      - name: Perform tests
        run: python3 perform_tests.py
